# azure-pipelines.yml - configuration for Azure Pipelines
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
trigger:
  - master
  - "feature/**"
stages:
  - stage: Default
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-16.04
        container: kazssym/cppunitx-builder:gcc
        steps:
          - bash: |
              autoreconf --install
            displayName: Bootstrap
          - bash: |
              mkdir -p _build
              cd _build
              ../configure
            displayName: Configure
          - bash: |
              cd _build
              make check
            displayName: Build
          - task: PublishTestResults@2
            condition: succeededOrFailed()
          - bash: |
              cd _build
              make dist VERSION="`sh ./config.status --version | sed -n '1s/^.* config\.status //p'`-$(Build.BuildNumber)"
              mkdir -p ../dist
              mv cppunitx-*.tar.* ../dist
            displayName: Make source archive
          - publish: dist
            artifact: dist
  - stage: TestUpload
    displayName: Test Upload
    dependsOn: Default
    condition: >-
      and(succeeded(),
          eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Upload
        pool:
          vmImage: ubuntu-16.04
        steps:
          - download: current
            artifact: dist
