# azure-pipelines.yml - configuration for Azure Pipelines
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
variables:
  - group: gpg
trigger:
  - master
  - release/**
  - feature/**
stages:
  - stage: Default
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-16.04
        container: kazssym/cppunitx-builder:gcc
        steps:
          - task: DownloadSecureFile@1
            name: gpgKeys
            inputs:
              secureFile: keys.asc
          - bash: |
              echo '$(GPG_PASSPHRASE)' | \
              sh ./setupkeys.sh '$(gpgKeys.secureFilePath)'
            displayName: Set up signing keys
          - bash: |
              autoreconf --install
            displayName: Bootstrap
          - bash: |
              mkdir -p _build
              cd _build
              ../configure --disable-static
            displayName: Configure
          - bash: |
              cd _build
              make check
            displayName: Build
          - task: PublishTestResults@2
            condition: succeededOrFailed()
          - bash: |
              cd _build
              make dist || exit $?
              mkdir -p ../dist
              mv -f cppunitx-*.tar.* ../dist
            displayName: Make source archive
          - publish: dist
            artifact: dist
  - stage: Test
    jobs:
      - job: Test
        strategy:
          matrix:
            Ubuntu:
              VM_IMAGE: ubuntu-latest
              CC: gcc
              CXX: g++
            macOS:
              VM_IMAGE: macOS-latest
              CC: clang
              CXX: clang++ -std=c++11
        continueOnError: true
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - checkout: none
          - download: current
            artifact: dist
          - bash: |
              $CXX --version
            displayName: Show versions
          - bash: |
              gzip -dc $(Pipeline.Workspace)/dist/cppunitx-*.tar.gz | tar -x
            displayName: Unpack
          - bash: |
              cd cppunitx-*
              ./configure --prefix=$(Build.BinariesDirectory)
            displayName: Configure
          - bash: |
              cd cppunitx-*
              make check
            displayName: Build
  - stage: Publish
    dependsOn: Default
    condition: >-
      and(succeeded(),
        or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
      - job: Publish
        pool:
          vmImage: ubuntu-16.04
        steps:
          - checkout: none
          - download: current
            artifact: dist
          - task: UniversalPackages@0
            inputs:
              command: publish
              publishDirectory: $(Pipeline.Workspace)/dist
              vstsFeedPublish: $(System.TeamProject)/cppunitx
              vstsFeedPackagePublish: cppunitx
              versionOption: patch
              packagePublishDescription: >
                C++UnitX is a lambda-based xUnit-style unit-testing framework
                for C++.
