# docker-compose.yml - compose file to build CppUnitX in a container
# Copyright (C) 2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "3"
services:
  builder:
    build: etc/gcc
    image: kazssym/cppunitx-builder:gcc
    network_mode: host
    volumes:
      - .:/usr/src/cppunitx
    working_dir: /usr/src/cppunitx
    command: make
