\input texinfo
@c %**start of header
@setfilename cppunitx.info
@settitle CppUnitX Reference Manual
@c %**end of header

@copying
Copyright @copyright{} 2018 Kaz Nishimura
@end copying

@titlepage
@title CppUnitX Reference Manual
@author Kaz Nishimura
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top CppUnitX
@end ifnottex

@node Introduction
@chapter Introduction

CppUnitX is another @var{x}Unit-style testing framework for modern C++.

@node Writing tests
@chapter Writing tests

@bye
