\input texinfo
@c %**start of header
@setfilename cppunitx.info
@settitle C++Unit@-X Reference Manual
@c %**end of header

@copying
Copyright @copyright{} 2018-2020 Kaz Nishimura
@end copying

@titlepage
@title C++Unit@-X Reference Manual
@author Kaz Nishimura
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top C++Unit@-X
@end ifnottex

@node Introduction
@chapter Introduction

C++Unit@-X is an xUnit-style lambda-based unit-testing framework for C++.

@node Writing tests
@chapter Writing tests

@bye
